name: tests

on:
  push:
    branches:
        - ravendb/v4.2

  pull_request:
    branches:
        - ravendb/v4.2
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ ubuntu-latest, windows-latest ]
        fail-fast: false  
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201

    - name: Install dependencies
      run: dotnet restore
      working-directory: ./test/Lucene.Net.Test

    - name: Test - Release
      run: dotnet test --configuration Release --no-restore /p:WarningLevel=0
      working-directory: ./test/Lucene.Net.Test
